# Generated by Django 2.0.5 on 2018-07-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('aggregator_id', models.AutoField(primary_key=True, serialize=False)),
                ('aggregator_consumption', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('appliance_consumption', models.BigIntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance_Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_consumption', models.BigIntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood_consumption', models.BigIntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=19)),
                ('kWh', models.BigIntegerField()),
                ('outdoor_temp', models.IntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.House')),
                ('neighborhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_consumption', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='readings',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='house',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.House'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Appliance_Type'),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('date_time', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id', 'kWh', 'outdoor_temp')},
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='appliance',
            unique_together={('appliance_id', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='aggregator',
            unique_together={('aggregator_id', 'region_id')},
        ),
    ]
