# Generated by Django 2.0.5 on 2018-07-31 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('aggregator_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('consumption', models.BigIntegerField()),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=2, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.House')),
                ('neighborhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='house',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='aggregator',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('reading_id', 'date', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id', 'consumption', 'temperature', 'humidity', 'wind_speed', 'wind_direction', 'cost')},
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='aggregator',
            unique_together={('aggregator_id', 'region_id')},
        ),
    ]
