# Generated by Django 2.1.1 on 2018-09-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='second',
            field=models.CharField(default='00', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='day',
            field=models.CharField(default='01', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='hour',
            field=models.CharField(default='00', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='month',
            field=models.CharField(default='01', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='year',
            field=models.CharField(default='2018', max_length=4, null=True),
        ),
    ]
