# Generated by Django 2.0.5 on 2018-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregator',
            name='full_name',
            field=models.CharField(default='full_name', max_length=51, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='full_name',
            field=models.CharField(default='full_name', max_length=106, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='full_name',
            field=models.CharField(default='full_name', max_length=78, primary_key=True, serialize=False),
        ),
    ]
