# Generated by Django 2.0.5 on 2018-07-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('date_time', 'reading_id', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id', 'kWh', 'outdoor_temp')},
        ),
    ]
