# Generated by Django 2.1.4 on 2019-01-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'house', 'neighborhood', 'aggregator', 'region', 'consumption', 'temperature', 'cost')},
        ),
    ]
