# Generated by Django 2.0.5 on 2018-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180809_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='cost',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='wind_direction',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='wind_speed',
            field=models.IntegerField(null=True),
        ),
    ]
