# Generated by Django 2.1.1 on 2018-09-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20180926_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='minute',
            field=models.CharField(default='00', max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('year', 'month', 'day', 'hour', 'minute', 'second'), ('reading_id', 'year', 'month', 'day', 'hour', 'minute', 'second', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id', 'consumption', 'temperature', 'cost')},
        ),
    ]
