# Generated by Django 2.1.1 on 2018-09-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180926_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='consumption_units',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='reading',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='hour',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='minute',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='second',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temperature_units',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('reading_id', 'year', 'month', 'day', 'hour', 'minute', 'second', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id', 'consumption', 'temperature', 'cost')},
        ),
    ]
