# Generated by Django 2.0.5 on 2018-09-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180810_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='consumption_units',
            field=models.CharField(default='kWh', max_length=3),
        ),
        migrations.AddField(
            model_name='reading',
            name='temperature_units',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
