# Generated by Django 2.1.1 on 2018-10-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20181005_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='aggregator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='house_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.House'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='neighborhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
    ]
