# Generated by Django 2.0.5 on 2018-06-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20180627_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregator',
            name='region_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
    ]
