# Generated by Django 2.1.1 on 2018-11-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20181025_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('voltage_a', models.BigIntegerField()),
                ('voltage_a_units', models.CharField(default='kWh', max_length=3)),
                ('voltage_b', models.BigIntegerField()),
                ('voltage_b_units', models.CharField(default='kWh', max_length=3)),
                ('voltage_c', models.BigIntegerField()),
                ('voltage_c_units', models.CharField(default='kWh', max_length=3)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('data_id', 'timestamp', 'voltage_a', 'voltage_a_units', 'voltage_b', 'voltage_b_units', 'voltage_c', 'voltage_c_units')},
        ),
    ]
