# Generated by Django 2.1.1 on 2018-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_auto_20181108_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
