# Generated by Django 2.1.1 on 2018-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20181108_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='voltage_a',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage_b',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage_c',
            field=models.FloatField(),
        ),
    ]
