# Generated by Django 2.0.5 on 2018-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance_type',
            name='description',
            field=models.TextField(),
        ),
    ]
