# Generated by Django 2.0.5 on 2018-06-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180627_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood_consumption', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood_consumption', models.BigIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='aggregator',
            unique_together={('aggregator_id', 'region_id')},
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='aggregator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='house',
            name='aggregator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator'),
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='house',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
    ]
