# Generated by Django 2.0.5 on 2018-06-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20180627_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.AutoField(primary_key=True, serialize=False)),
                ('appliance_consumption', models.BigIntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=19)),
                ('kWh', models.BigIntegerField()),
                ('outdoor_temp', models.IntegerField()),
                ('aggregator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Aggregator')),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='neighborhood_consumption',
            new_name='house_consumption',
        ),
        migrations.AddField(
            model_name='readings',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.House'),
        ),
        migrations.AddField(
            model_name='readings',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='readings',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.House'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='neighborhood_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Neighborhood'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Region'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.Appliance_Type'),
        ),
        migrations.AlterUniqueTogether(
            name='readings',
            unique_together={('date_time', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='appliance',
            unique_together={('appliance_id', 'house_id', 'neighborhood_id', 'aggregator_id', 'region_id')},
        ),
    ]
